export function renderFooter(doc: PDFKit.PDFDocument): void {
  // Add a new page for footer/disclaimer if we're too far down
  if (doc.y > 650) {
    doc.addPage();
  }

  doc.moveDown(2);

  // Medical Disclaimer
  doc
    .fontSize(12)
    .fillColor("#000000")
    .text("Medical Disclaimer", { underline: true });
  doc.moveDown(0.5);

  doc
    .fontSize(9)
    .fillColor("#333333")
    .text(
      "This report is for informational purposes only and is not intended to be a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or treatment.",
      {
        align: "justify",
      },
    );

  doc.moveDown(0.5);

  doc.text(
    "The information in this report is self-reported by the patient and has not been verified by a healthcare professional. BioStak is a tracking platform and does not provide medical advice or recommendations.",
    {
      align: "justify",
    },
  );

  doc.moveDown(1);

  // Legal Notice
  doc.fontSize(8).fillColor("#666666").text(
    "Generated by BioStak © " + new Date().getFullYear(),
    {
      align: "center",
    },
  );

  doc.fillColor("#000000");
}
